### PR TITLE
Add X-Fan and vertical swing support

### PR DESCRIPTION
**Pull request by denniedegroot**
Added X-Fan and vertical swing support. Fully tested and working on a Tosot Bora.

### CODE REVIEW

**Comment by denniedegroot** [comment]
The German translation is maybe sometimes not correct. Could you maybe check this?

**Comment by aivus** [comment]
Hey @denniedegroot 👋 

Thank you. I'll review this changes soon.

> The German translation is probably for some items not correct. Could you maybe check this?

I'm not a German speaker and I'm using Google Translate for DE translations, so I cannot help here.

**Comment by denniedegroot** [comment]
I also made I change to convert to the thermostat capability.
After the conversion it uses native Homey thermostat capabilities which mean the app uses the correct colors for heating/cooling and Google Home can be used to set heating/cooling.

**Comment by aivus** [comment]
Hey @denniedegroot 

Thank you. I'll merge X-Fan and Vertical swing capabilities in #42.

Converting capability from `hvac_mode` to `thermostat_mode` will be handled separately.

**Comment by denniedegroot** [comment]
Ok great, I just saw you also changed some translations. As I am Dutch I had a laugh at some translations (google translate errors), maybe before you make a release I could make a new PR with the correct Dutch translations?

**Comment by aivus** [comment]
I'll be appreciated, if you add correct translations directly in PR #42 or create a PR to the `add_xfan_vertical_swing` branch.

**Comment by denniedegroot** [comment]
I just did, see #43.

**Comment by aivus** [comment]
I've created a ticket for renaming `hvac_mode` to `thermostat_mode`: #46 just not to mix different things in one PR.

X-Fan/vertical swing merged and released already in v0.3.0.

Thanks again

**Pull request closed without merging**
